name: Build LGL Menu
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configura Android SDK e Accetta Licenze
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'

      - name: Accetta Licenze Manualmente
        run: yes | sdkmanager --licenses || true

      - name: Configura Gradle 7.5 con Action Ufficiale
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 7.5

      - name: Permessi Gradle
        run: chmod +x gradlew

      - name: Compila APK
        run: ./gradlew assembleDebug --no-daemon
      
